

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class VanBan
 */
@WebServlet("/VanBan")
public class VanBan extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public VanBan() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
    protected void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		// TODO Auto-generated method stub
		res.setCharacterEncoding("UTF-8");
        PrintWriter out = res.getWriter();
        res.setContentType("text/html");
        out.println("<html>"
        		+ "<head>"
        		+ "<title>Viện Kiểm Sát Quận 8</title>\r\n"
        		+ "    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" />\r\n"
        		+ "    <link rel=\"stylesheet\" href=\"CSS/template.css\" />\r\n"
        		+ "    <link rel=\"stylesheet\" href=\"CSS/vbpl.css\" />\r\n"
        		+ "    <script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n"
        		+ "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>"
               + "</head>");
                out.println("<header>\r\n"
                		+ "    <div id=\"head\">\r\n"
                		+ "        <img src=\"Hinh/topbar.png\" style=\"width: 100%;\">\r\n"
                		+ "    </div>\r\n"
                		+ "    <!-- Header + topbar -->\r\n"
                		+ "    <div id=\"menu\">\r\n"
                		+ "        <!-- Header -->\r\n"
                		+ "\r\n"
                		+ "        <!-- Topbar -->\r\n"
                		+ "        <div class=\"header\">\r\n"
                		+ "            <ul>\r\n"
                		+ "                <a href=\"Home.jsp\" class=\" label_home\"> <i class=\"fas fa-home\"></i> </a>\r\n"
                		+ "                <li><a href=\"#\">Giới Thiệu <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n"
                		+ "                    <!-- menu con sổ xuống cấp 1 -->\r\n"
                		+ "                    <ul>\r\n"
                		+ "                        <li class=\"submenu\"><a href=\"home3.jsp\">Hệ thống tổ chức</a></li>\r\n"
                		+ "                        <li class=\"submenu\"><a href=\"home1.jsp\">Chức năng, nhiệm vụ</a> </li>\r\n"
                		+ "                        <!-- menu con sổ ngang cấp 2 -->\r\n"
                		+ "                        <!--<ul>\r\n"
                		+ "                                <li><a href=\"home2.1.html\">Viện trưởng VKSND TP. Hồ Chí Minh qua các thời kỳ</a></li>\r\n"
                		+ "                                <li><a href=\"home2.2.html\">Phó viện trưởng VKSND TP. Hồ Chí Minh qua các thời kỳ</a>\r\n"
                		+ "                                </li>\r\n"
                		+ "                            </ul> -->\r\n"
                		+ "                    </ul>\r\n"
                		+ "                </li>\r\n"
                		+ "                <li><a href=\"#\">Tin Tức <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n"
                		+ "                    <ul>\r\n"
                		+ "                        <li class=\"submenu\"><a href=\"tnv.jsp\">Tin nghiệp vụ</a></li>\r\n"
                		+ "                        <li class=\"submenu\"> <a href=\"ttt.jsp\">Tin tổng hợp</a></li>\r\n"
                		+ "                        <li class=\"submenu\"> <a href=\"hddt.jsp\">Hoạt động đoàn thể</a></li>\r\n"
                		+ "                        <li class=\"submenu\"> <a href=\"hvltb.jsp\">Học và làm theo Bác</a></li>\r\n"
                		+ "\r\n"
                		+ "                    </ul>\r\n"
                		+ "                </li>\r\n"
                		+ "                <li><a href=\"#\">Văn Bản <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n"
                		+ "                    <ul>\r\n"
                		+ "                        <li class=\"submenu\"><a href=\"https://vkstphcm.gov.vn/vanban\">Văn bản pháp luật</a></li>\r\n"
                		+ "\r\n"
                		+ "                    </ul>\r\n"
                		+ "                </li>\r\n"
                		+ "                <li><a href=\"login.jsp\">Đăng Nhập</a></li>\r\n"
                		+ "                <li><a href=\"lienhe.jsp\">Liên Hệ</a></li>\r\n"
                		+ "            </ul>\r\n"
                		+ "            <div class=\"search-box\">\r\n"
                		+ "                <input type=\"text\" placeholder=\"Tìm kiếm\">\r\n"
                		+ "                <button class=\"search1\" style=\"border:none;\">\r\n"
                		+ "                    <i class=\"fas fa-search\"></i>\r\n"
                		+ "                </button>\r\n"
                		+ "            </div>\r\n"
                		+ "        </div>\r\n"
                		+ "    </div>\r\n"
                		+ "</header>"
                		+"<script>\r\n"
                		+ "    // When the user scrolls the page, execute myFunction\r\n"
                		+ "    window.onscroll = function () { myFunction() };\r\n"
                		+ "\r\n"
                		+ "    // Get the header\r\n"
                		+ "    var header = document.getElementById(\"menu\");\r\n"
                		+ "\r\n"
                		+ "    // Get the offset position of the navbar\r\n"
                		+ "    var sticky = header.offsetTop;\r\n"
                		+ "\r\n"
                		+ "    // Add the sticky class to the header when you reach its scroll position. Remove \"sticky\" when you leave the scroll position\r\n"
                		+ "    function myFunction() {\r\n"
                		+ "        if (window.pageYOffset > sticky) {\r\n"
                		+ "            header.classList.add(\"sticky\");\r\n"
                		+ "        } else {\r\n"
                		+ "            header.classList.remove(\"sticky\");\r\n"
                		+ "        }\r\n"
                		+ "    }\r\n"
                		+ "\r\n"
                		+ "</script>"
                		+ "<body>\r\n"
                		+ "\r\n"
                		+ "    <!-- div lớn -->\r\n"
                		+ "    <div class=\"row\">\r\n"
                		+ "        <!-- div 2 box-notice-->\r\n"
                		+ "        <div class=\" d-none d-lg-block \">\r\n"
                		+ "            <!--div lớn box-notice 1 gồm h4-->\r\n"
                		+ "            <div class=\"card linhvuc-box \">\r\n"
                		+ "                <!--div h4-->\r\n"
                		+ "                <div class=\"card-header\">\r\n"
                		+ "                    <h4 class=\"card-title\">Lĩnh vực</h4>\r\n"
                		+ "                </div>\r\n"
                		+ "                <!--div lớn box-notice 1 không gồm h4 -->\r\n"
                		+ "                <div class=\"card-body\">\r\n"
                		+ "                    <!--div con box-notice 1-->\r\n"
                		+ "                    <div class=\"container\">\r\n"
                		+ "                        <!--list-->\r\n"
                		+ "                        <ul class=\"list-linhvuc\">\r\n"
                		+ "                            <!-- ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=1\" class=\"ng-binding\" href=\"?field=1\">\r\n"
                		+ "                                    Công tác Đảng\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=2\" class=\"ng-binding\" href=\"?field=2\">\r\n"
                		+ "                                    Dân sự - HNGĐ\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=3\" class=\"ng-binding\" href=\"?field=3\">\r\n"
                		+ "                                    Hành chính\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=4\" class=\"ng-binding\" href=\"?field=4\">\r\n"
                		+ "                                    Kinh doanh thương mại\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=5\" class=\"ng-binding\" href=\"?field=5\">\r\n"
                		+ "                                    Lao động\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=6\" class=\"ng-binding\" href=\"?field=6\">\r\n"
                		+ "                                    Hình sự\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=7\" class=\"ng-binding\" href=\"?field=7\">\r\n"
                		+ "                                    Giam giữ - THA - Khiếu tố\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=8\" class=\"ng-binding\" href=\"?field=8\">\r\n"
                		+ "                                    Thống kê tội phạm\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=9\" class=\"ng-binding\" href=\"?field=9\">\r\n"
                		+ "                                    Tổ chức cán bộ - thanh tra\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=10\" class=\"ng-binding\" href=\"?field=10\">\r\n"
                		+ "                                    Văn phòng tổng hợp\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLinhVuc\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=11\" class=\"ng-binding\" href=\"?field=11\">\r\n"
                		+ "                                    Lĩnh vực khác\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLinhVuc -->\r\n"
                		+ "                        </ul>\r\n"
                		+ "                    </div>\r\n"
                		+ "                </div>\r\n"
                		+ "            </div>\r\n"
                		+ "            <!--div lớn box2 gồm h4-->\r\n"
                		+ "            <div class=\"card loaivb-box\">\r\n"
                		+ "                <div class=\"card-header\">\r\n"
                		+ "                    <h4 class=\"card-title\">Loại văn bản</h4>\r\n"
                		+ "                </div>\r\n"
                		+ "                <!--div lớn box2 không gồm h4-->\r\n"
                		+ "                <div class=\"card-body\">\r\n"
                		+ "                    <!--div con box2-->\r\n"
                		+ "                    <div class=\"container\">\r\n"
                		+ "                        <!--list-->\r\n"
                		+ "                        <ul class=\" list-loaivb\">\r\n"
                		+ "                            <!-- ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=8\" class=\"ng-binding\" href=\"?field=8\">\r\n"
                		+ "                                    Thông báo\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=1\" class=\"ng-binding\" href=\"?field=1\">\r\n"
                		+ "                                    Công văn\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=2\" class=\"ng-binding\" href=\"?field=2\">\r\n"
                		+ "                                    Chỉ thị\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=3\" class=\"ng-binding\" href=\"?field=3\">\r\n"
                		+ "                                    Hướng dẫn\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=4\" class=\"ng-binding\" href=\"?field=4\">\r\n"
                		+ "                                    Luật\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=5\" class=\"ng-binding\" href=\"?field=5\">\r\n"
                		+ "                                    Quy định\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=6\" class=\"ng-binding\" href=\"?field=6\">\r\n"
                		+ "                                    Quy chế\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=7\" class=\"ng-binding\" href=\"?field=7\">\r\n"
                		+ "                                    Quyết định\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=9\" class=\"ng-binding\" href=\"?field=9\">\r\n"
                		+ "                                    Thông tư\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=10\" class=\"ng-binding\" href=\"?field=10\">\r\n"
                		+ "                                    Thông tư liên tịch\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=11\" class=\"ng-binding\" href=\"?field=11\">\r\n"
                		+ "                                    Kế hoạch\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            <li data-ng-repeat=\"option in data.listOfLoaiVB\" class=\"ng-scope\">\r\n"
                		+ "                                <a ng-href=\"?field=12\" class=\"ng-binding\" href=\"?field=12\">\r\n"
                		+ "                                    Chương trình\r\n"
                		+ "                                </a>\r\n"
                		+ "                            </li><!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                        </ul>\r\n"
                		+ "                    </div>\r\n"
                		+ "                </div>\r\n"
                		+ "            </div>\r\n"
                		+ "        </div>\r\n"
                		+ "        <!--tim kiem-->\r\n"
                		+ "        <div class=\"search-data\">\r\n"
                		+ "            <div class=\"box-search\">\r\n"
                		+ "                <!--div lớn-->\r\n"
                		+ "                <div class=\"card-search \">\r\n"
                		+ "                    <!--div lớn tìm kiếm-->\r\n"
                		+ "                    <div class=\"card-body-1 search-box-box  \">\r\n"
                		+ "                        <div class=\"searchbox-header\">\r\n"
                		+ "                            <h4 class=\"title\">Tìm kiếm văn bản</h4>\r\n"
                		+ "                        </div>\r\n"
                		+ "                        <div class=\"form-input-put\">\r\n"
                		+ "                            <label class=\"col-md-2 col-form-label\">Nhập từ khóa</label>\r\n"
                		+ "                            <div class=\"input-group\">\r\n"
                		+ "                                <input class=\"form-control ng-pristine ng-untouched ng-valid ng-empty\"\r\n"
                		+ "                                    id=\"txtTextSearch\" name=\"textSearch\" ng-model=\"condition.textSearch\" type=\"text\"\r\n"
                		+ "                                    placeholder=\"từ khóa tìm kiếm\" aria-label=\"\">\r\n"
                		+ "                            </div>\r\n"
                		+ "                        </div>\r\n"
                		+ "                    </div>\r\n"
                		+ "                    <div class=\"form-input-put\">\r\n"
                		+ "                        <label class=\"col-md-2 col-form-label\">Loại văn bản</label>\r\n"
                		+ "                        <div class=\"col-md-10\">\r\n"
                		+ "                            <select class=\"form-control ng-pristine ng-untouched ng-valid ng-empty\"\r\n"
                		+ "                                ng-model=\"condition.loaiVBId\">\r\n"
                		+ "                                <option value=\"\" selected=\"selected\">Chọn loại văn bản</option>\r\n"
                		+ "                                <!-- ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:8\">Thông báo</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:1\">Công văn</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:2\">Chỉ thị</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:3\">Hướng dẫn</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:4\">Luật</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:5\">Quy định</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:6\">Quy chế</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:7\">Quyết định</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:9\">Thông tư</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:10\">Thông tư liên tịch</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:11\">Kế hoạch</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                                <option ng-repeat=\"option in data.listOfLoaiVB\" ng-value=\"option.Id\"\r\n"
                		+ "                                    class=\"ng-binding ng-scope\" value=\"number:12\">Chương trình</option>\r\n"
                		+ "                                <!-- end ngRepeat: option in data.listOfLoaiVB -->\r\n"
                		+ "                            </select>\r\n"
                		+ "                        </div>\r\n"
                		+ "                    </div>\r\n"
                		+ "                    <div class=\"form-input-put \">\r\n"
                		+ "                        <label class=\"col-md-2 col-form-label\">Ngày ban hành</label>\r\n"
                		+ "                        <div class=\"col-md-5\">\r\n"
                		+ "                            <div class=\"input-group-1\">\r\n"
                		+ "                                <input class=\"form-control ng-pristine ng-untouched ng-valid ng-empty\"\r\n"
                		+ "                                    id=\"txtTextSearch\" name=\"textSearch\" ng-model=\"condition.textSearch\" type=\"date\"\r\n"
                		+ "                                    aria-label=\"\">\r\n"
                		+ "\r\n"
                		+ "                                <input class=\"form-control ng-pristine ng-untouched ng-valid ng-empty\"\r\n"
                		+ "                                    id=\"txtTextSearch1\" name=\"textSearch\" ng-model=\"condition.textSearch\" type=\"date\"\r\n"
                		+ "                                    aria-label=\"\">\r\n"
                		+ "                            </div>\r\n"
                		+ "                            <div class=\"form-input-put\">\r\n"
                		+ "                                <button type=\"button\" id=\"btn-search\" class=\"btn btn-primary\" ng-click=\"search(1)\"><a "
                		+ " href='vbpl.jsp'>Tìm\r\n"
                		+ "    kiếm\r\n"
                		+ "   </a></button>\r\n"
                		+ "                            </div>\r\n"
                		+ "                        </div>\r\n"
                		+ "                    </div>\r\n"
                		+ "                </div>\r\n"
                		+ "            </div>");

               

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/vksq8", "root", "");
            String sql = "SELECT * FROM vanban";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            out.println( "<table class='table table-bordered'>"
            		
            +"<thead>");
            out.println("<tr><th>STT</th><th>Số hiệu</th><th>Trích yếu nội dung</th><th>Lĩnh vực</th><th>Loại văn bản</th><th>Ngày ban hành</th></tr>");
            out.println("</thead>");
            while (rs.next()) {
              
                String STT = rs.getString("STT");
                String SoHieu = rs.getString("SoHieu");
                String TrichYeuNoiDung = rs.getString("TrichYeuNoiDung");
                String LinhVuc = rs.getString("LinhVuc");
                String LoaiVanBan = rs.getString("LoaiVanBan");
                Date NgayBanHanh = rs.getDate("NgayBanHanh");
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                String formattedNgayBanHanh = dateFormat.format(NgayBanHanh);
                

out.println("<tbody>");

out.println("<tr><td>" + STT + "</td><td>" + SoHieu + "</td><td>"+ TrichYeuNoiDung 
		+ "</td><td>" + LinhVuc + "</td><td>" + LoaiVanBan + "</td><td>" + formattedNgayBanHanh + "</td></tr>");

            }
            out.println(" </tbody>\r\n"
            		+ "            </table>\r\n"
            		+ "\r\n"
            		+ "            <div id=\"pag-cover\">\r\n"
            		+ "                <div id=\"pg-links\">\r\n"
            		+ "                    <div class=\"td arr-cover\">\r\n"
            		+ "                        <div class=\"arrow\" id=\"l-arrow\"><i class=\"fas fa-chevron-circle-left\"></i></div>\r\n"
            		+ "                    </div>\r\n"
            		+ "                    <div class=\"td\">\r\n"
            		+ "                        <div id=\"links\">\r\n"
            		+ "                            <div class=\"pg-link\"><span>4</span></div>\r\n"
            		+ "                            <div class=\"pg-link\" id=\"m-pg-link\"><span>5</span></div>\r\n"
            		+ "                            <div class=\"pg-link\"><span>6</span></div>\r\n"
            		+ "                        </div>\r\n"
            		+ "                    </div>\r\n"
            		+ "                    <div class=\"td arr-cover\">\r\n"
            		+ "                        <div class=\"arrow\" id=\"r-arrow\"><i class=\"fas fa-chevron-circle-right\"></i></div>\r\n"
            		+ "                    </div>\r\n"
            		+ "                </div>\r\n"
            		+ "            </div>\r\n"
            		+ "            <script>\r\n"
            		+ "                $(function () {\r\n"
            		+ "                    var pg_links = $(\".pg-link\"),\r\n"
            		+ "                        h_elm = $(\"#m-pg-link\"),\r\n"
            		+ "                        curr = 5,\r\n"
            		+ "                        _this,\r\n"
            		+ "                        _class,\r\n"
            		+ "                        _id,\r\n"
            		+ "                        __this,\r\n"
            		+ "                        _num,\r\n"
            		+ "                        i = 0;\r\n"
            		+ "\r\n"
            		+ "                    function changeNumbers(flag) {\r\n"
            		+ "                        if ((curr > 2 && flag == 0) || flag) {\r\n"
            		+ "                            if (curr == 1) {\r\n"
            		+ "                                curr = 2;\r\n"
            		+ "                                h_elm.removeClass(\"left\");\r\n"
            		+ "                                return;\r\n"
            		+ "                            }\r\n"
            		+ "\r\n"
            		+ "                            $(pg_links).each(function () {\r\n"
            		+ "                                __this = $(this).find(\"span\");\r\n"
            		+ "                                _num = parseInt(__this.text());\r\n"
            		+ "\r\n"
            		+ "                                if (flag) _num += 1;\r\n"
            		+ "                                else _num -= 1;\r\n"
            		+ "\r\n"
            		+ "                                ++i;\r\n"
            		+ "\r\n"
            		+ "                                $(this).addClass(\"s-hide\");\r\n"
            		+ "\r\n"
            		+ "                                __this.text(_num);\r\n"
            		+ "\r\n"
            		+ "                                setTimeout(function (link) {\r\n"
            		+ "                                    link.removeClass(\"s-hide\");\r\n"
            		+ "                                }, 150, $(this));\r\n"
            		+ "\r\n"
            		+ "                                if (i == 2) curr = _num;\r\n"
            		+ "                            });\r\n"
            		+ "\r\n"
            		+ "                            i = 0;\r\n"
            		+ "                        } else {\r\n"
            		+ "                            if (curr == 2 && flag == 0) {\r\n"
            		+ "                                curr = 1;\r\n"
            		+ "                                h_elm.addClass(\"left\");\r\n"
            		+ "                            }\r\n"
            		+ "                        }\r\n"
            		+ "                    }\r\n"
            		+ "\r\n"
            		+ "                    function changeLinks() {\r\n"
            		+ "                        _this = $(this);\r\n"
            		+ "                        _class = _this.attr(\"class\").trim().toLowerCase();\r\n"
            		+ "\r\n"
            		+ "                        if (_class == \"arrow\") {\r\n"
            		+ "                            _id = _this.attr(\"id\").trim().toLowerCase();\r\n"
            		+ "\r\n"
            		+ "                            if (_id == \"l-arrow\") changeNumbers(0);\r\n"
            		+ "                            else changeNumbers(1);\r\n"
            		+ "                        } else {\r\n"
            		+ "                            if (parseInt(_this.text().trim()) < curr) changeNumbers(0);\r\n"
            		+ "                            else changeNumbers(1);\r\n"
            		+ "                        }\r\n"
            		+ "                    }\r\n"
            		+ "\r\n"
            		+ "                    $(\".pg-link,.arrow\").on(\"click\", changeLinks);\r\n"
            		+ "                });\r\n"
            		+ "            </script>\r\n"
            		+ "\r\n"
            		+ "        </div>\r\n"
            		+ "\r\n"
            		+ "       \r\n"
            		+ "    </div>\r\n"
            		+ "</body>\r\n"
            		+ "<footer class=\"footer\">\r\n"
            		+ "    <img src=\"Hinh/logo_brand.png\" alt=\"logo\">\r\n"
            		+ "    <h3>TRANG THÔNG TIN ĐIỆN TỬ VIỆN KIỂM SÁT NHÂN DÂN QUẬN 8</h3>\r\n"
            		+ "    <p>Trụ sở: 11 Dương Quang Đông, Phường 5, Quận 8, Thành phố Hồ Chí Minh ; Điện thoại: 028 3851 5859 <br>\r\n"
            		+ "        Trưởng Ban biên tập: Viện trưởng VKSND Quận 8<br>\r\n"
            		+ "        <br>\r\n"
            		+ "        © Bản quyền thuộc về VKSND Quận 8.\r\n"
            		+ "    </p>\r\n"
            		+ "</footer>");
            out.println("</body></html>");
            con.close();
        } 
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            out.println("error: " + e.getMessage());
}
	}


	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
